### ISSUE TITLE
GPIO methods

### ISSUE THREAD

**Issue by KipCrossing** [lvidarte/esp8266#1]
Just following the example in the docs [here](https://github.com/lvidarte/esp8266/wiki/MicroPython%3A-LED) and noticed that `.high()` and `.low()` methods arent on the ESP8266; instead, it uses the `.on()` and `.off()` methods.

See the [MicroPython docs](http://docs.micropython.org/en/latest/esp8266/quickref.html#pins-and-gpio)

**Comment by lvidarte** [comment]
Yep, removed in version 1.9
https://github.com/micropython/micropython/releases/tag/v1.9

> - replace deprecated Pin.high()/low() methods with .__call__(1/0)

Thanks

**Comment by lvidarte** [comment]
This code works with v1.8.7
